### ISSUE TITLE
Divide by zero error when completing the application without error.

### ISSUE THREAD

**Issue by skylerberg** [SageBerg/LearnYouATypist#1]
I ran it and it broke :(.

But seriously, I see that you are aware of this in your commit message. I just wanted to drop in and say that this is a great idea. I hate how every time I look for typing apps I find something that is so fancy it is unusable and entirely unrealistic. I am looking forward to using this!

**Comment by SageBerg** [comment]
Yeah, I need to change the data types, but I was tired and went to bed.

One of my main problems with typing apps is that they don't have much content, so I'll end up seeing the same lessons again and again. Adding content is easy.

I also don't like being alerted to my errors. Often, in the real world, nobody tells you if you make a typing mistake. So, when you're practicing, it's best to learn to see the mistakes yourself.

I'm writing a basic local application to start with and if I like it enough, I'll make it into a website.

**Comment by skylerberg** [comment]
The mistakes thing is big. You really do need to be able to find your own mistakes.

Another thing that bugs me about typing sites is when they count things that you correct as mistakes. Basically, if you can correct your mistakes it should not count as a mistake, it should just slow you down like it does in real life. I have even seen typing applications where backspace doesn't work.

It is important to allow custom content too. For example, practising typing code requires different lessons than typing prose.

**Comment by SageBerg** [comment]
It would be nice to see how much we're relying on backspacing, if we want to get better at not making mistakes in the first place. I might provided output that counts the number of backspaces during a session. Disallowing backspace altogether is draconian and doesn't model the real world.

You've got some good ideas here that I'll put in my TODO list for this project. 

I fixed the error, so I'll close this issue.
